### ISSUE TITLE
Archive in subfolder with year of the mail

### ISSUE THREAD

**Issue by Vercety87** [Infomaniak/ios-kMail#1388]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Like in Thunderbird, being able to archive mail directly in an subfolder related to the year of the mail.

**Additional context**

![image](https://github.com/Infomaniak/ios-kDrive/assets/44375309/c3d43120-8164-4dda-9068-2b07003efa38)

**Comment by PhilippeWeidmann** [comment]
Hi,
Thank you for your feedback. As the mobile app directly communicates with the webmail it would be better to do a feature request here: https://feedback.userreport.com/5f64b035-33e5-4e71-9572-dc9d1d451c18/
