### ISSUE TITLE
Profile Bottom Sheet Animates Twice on Launch

### ISSUE THREAD

**Issue by riadmahi** [Infomaniak/ios-kMail#1584]
1. Go to Home
2. Click on Profile picture
3. See error

**Expected behavior**
Animation should appear 1 time

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 15
 - iOS version: iOS 18.0
 - App version: 1.2.3-2

**Comment by PhilippeWeidmann** [comment]
Hi, thank you for your report.

The issue was resolved with latest build 1.2.4. It's is available since this morning on the App Store.
