### ISSUE TITLE
OpenPGP support for encryption

### ISSUE THREAD

**Issue by moon-cacke** [Infomaniak/ios-kMail#1589]
Hi,

First thanks a lot for your amazing products.

Adding support for OpenPGP encryption would be really really amazing, currently there is no opensource client that support OpenPGP on iOS

The only opensource solution for the moment is PGPro, but its not a full mail client and rely on the native Mail app.

You could use its code for an easy integration of the feature.

Thanks a lot :)

**Comment by PhilippeWeidmann** [comment]
Hi, sorry for the delay.

We tend to develop those features along side the whole mail platform so this wouldn't be only on mobile but also on our webmail.

You can make a feature suggestion here:

French: https://feedback.userreport.com/d6b0e711-0c77-459c-9d06-79f92264f221/
English: https://feedback.userreport.com/5f64b035-33e5-4e71-9572-dc9d1d451c18/
