### ISSUE TITLE
Impossible to delete an email

### ISSUE THREAD

**Issue by julienallexandre** [Infomaniak/ios-kMail#727]
Description :
When I'm in the social networks folder I have an e-mail that won't disappear into the recycle bin

Video : 
https://user-images.githubusercontent.com/58303569/235872553-bb3c9685-14e7-493a-b739-a7e5db9aecf0.mp4

Smartphone :
 - Device: iPhone 13 Pro
 - iOS version: 16.4.1 (a)
 - App version: 1.0.0-beta64

**Comment by JorisBodin** [comment]
Fix in Build 71
