### ISSUE TITLE
No display of new e-mails in specific folders

### ISSUE THREAD

**Issue by julienallexandre** [Infomaniak/ios-kMail#729]
Description:
I don't have any notifications or items showing me a mail in specific folders

Video:
https://user-images.githubusercontent.com/58303569/235888460-84400707-4170-442f-8a80-53c48ac32155.mov

Smartphone:
 - Device: iPhone 13 Pro
 - iOS version: 16.4.1 (a)
 - App version: 1.0.0-beta64

**Comment by PhilippeWeidmann** [comment]
Hi, you should have a "dot" marker next to the folder title. I see that you have the version 1.0.0-beta64. This feature was introduced in a later release please try it on the latest release (1.0.3).

Regarding push notifications for a specific folder we are still discussing internally on the best way to do it.

**Comment by PhilippeWeidmann** [comment]
Feel free to reopen the issue if your problem still exists
