### ISSUE TITLE
Unable to send mail via iOS app

### ISSUE THREAD

**Issue by Vercety87** [Infomaniak/ios-kMail#755]
**Description**
Can't send new email via the Kmail app. No problem with reply. 

**Steps to reproduce**
1. Write an new email
2. Send the email
3. See error "L'opération n'a pas pu s'achever.
(MailCore.MailError erreur 1.)"

**Screenshots**

![image](https://github.com/Infomaniak/ios-kMail/assets/44375309/dd5d49af-8c32-42ca-8326-d37c25b47419)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 pro
 - iOS version: 16.5
 - App version: 1.0.0 (70)

**Comment by adrien-coye** [comment]
Hello @Vercety87, I’m Adrien. I’m on the dev team.
What you are experiencing is a server error. 
As I cannot reproduce here I can only ask you to try to log-out and log back in again or try to reinstall the app.

On our side we are making changes to track those kind of issues and we should be able to provide a more permanent fix soon.
Thanks.

**Comment by JorisBodin** [comment]
@Vercety87 The email have an attachment or not?

**Comment by JorisBodin** [comment]
Fix yesterday
https://github.com/Infomaniak/ios-kMail/pull/753
