### ISSUE TITLE
No push notification when receiving new email.

### ISSUE THREAD

**Issue by Vercety87** [Infomaniak/ios-kMail#757]
**Description**
No push notification when receiving new email.

**Steps to reproduce**
1. Send an email from another provider to my infomaniak email
2. Wait to receive an notification on you device with Kmail app installed
3. No push notifications and no badge on the app icons
4. Open the Kmail app, the app retrieve new mail

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max / iPhone 14 pro / iPad Pro (12,9 pouces) (4e génération)
 - iOS version: all 3 devices with iOS/iPad OS 16.5
 - App version: 1.0.0 (70)

**Additional context**
Weird think about that, yesterday when I installed the app on my iPhone 14 pro, I wasn’t able to receive push notification on my phone. But when I wake up this morning it was ok.

But on my iPad still no push notification.

On my wife iPhone 13 Pro, with her infomaniak account she doesn’t receive any push notifications. We set up our phone with Kmail app at the same time yesterday.

On the three devices, notifications are ON, on the kmail app and in the iphone settings for kmail app. And background refresh is ON for Kmail in the iPhone settings.

**Comment by Vercety87** [comment]
No more problem also on my wife phone. Without doing anything.

**Comment by JorisBodin** [comment]
> Mon iPad a commencé à recevoir des notifications push. C'est bizarre car il y a un délai avant de recevoir la première notification, mais après ça va. Je vais vérifier l'iPhone de ma femme ce soir pour voir si tout va bien de son côté.

For the moment there is a delay of about 1H MAX before receiving the first notifications
