### ISSUE TITLE
Catch all inbox no new mail and display old mail

### ISSUE THREAD

**Issue by Vercety87** [Infomaniak/ios-kMail#818]
**Description**
Since 1.00 update on iOS. My catchall inbox is stuck with one old email and doesn't retrieve new email. Even when I delete the old mail from Infomaniak webmail. 

**Smartphone (please complete the following information):**
 - Device: iPhone 14 pro
 - iOS version: iOS 16.5
 - App version: 1.0.0

![image](https://github.com/Infomaniak/ios-kMail/assets/44375309/d2237dfb-a311-4a26-befa-a7e6121d5fb1)

**Comment by PhilippeWeidmann** [comment]
Hi, we will need more details about your issue. As the issues are public could you please send us the email address associated with the mailbox via a TestFlight feedback to avoid disclosing private informations ?

**Comment by Vercety87** [comment]
Seems to be ok since 1.0.0 (76) update. I no longer see old email on my catchall inbox.

**Comment by PhilippeWeidmann** [comment]
We fixed several issues regarding mail sorting in the latest builds (76-77-78) if the problem comes back would you mind reopening this issue ?

**Comment by Vercety87** [comment]
Thanks, no more problem with theses updates.
