### ISSUE TITLE
Add notifications interaction

### ISSUE THREAD

**Issue by Vercety87** [Infomaniak/ios-kMail#882]
Would be cool to add interaction from the notifications of the app. 

Like the Apple Mail app : 
![image](https://github.com/Infomaniak/ios-kMail/assets/44375309/b0dd3ae5-a2c8-4d95-b957-ac3e461180f0)

Thanks

**Comment by PhilippeWeidmann** [comment]
Hi, thank you for your feedback. 
This is feature is already on our TODO list and we will be available in an upcoming release.
