### ISSUE TITLE
Message Display Mode: add option for simple list display ("Messages")

### ISSUE THREAD

**Issue by docgyneco69** [Infomaniak/ios-kMail#907]
iOSkMail single message display mode is "Discussions". When will the "Messages" display option be implemented too ?
In addition, current "Discussions" mode could do with the customisation of each conversation's message sorting key: not clear at all currently how it works/what is shown (recent answers shown above newly received messages in some cases etc.) 
This would provide a simple fix to make the app useful.

**Comment by PhilippeWeidmann** [comment]
Hi, this is a highly demanded feature. We will do it in an upcoming release.

**Comment by valentinperignon** [comment]
The feature is now available in the app.
