### ISSUE TITLE
Calendar invitations

### ISSUE THREAD

**Issue by docgyneco69** [Infomaniak/ios-kMail#908]
Emails with calendar invitations shows with not actionable links in the app and therefore useless. Could you link the app with iOS local handlers (Apple Cal, MS Teams) ?

**Comment by PhilippeWeidmann** [comment]
Hi, thank you for your feedback. This is planned and we will do it in an upcoming release.

**Comment by PhilippeWeidmann** [comment]
Will be available in the next beta soon. Resolved with #1243
